
<table width="60%">
  <tr><td height="50"></td></tr>
  <tr>
    <td align="left">
      <a href="http://www.sti-innsbruck.at/"><img src="../Images/sti-innsbruck-logo.jpg" width="45" height="90" alt="STI-Innsbruck Logo" border="0"></a>
    </td>
    <td align="right">
      <a href="http://www.uibk.ac.at/ipoint/"><img src="../Images/uibk_logo.png" width="45" height="90" alt="University Innsbruck Logo" border="0"></a>
    </td>
  </tr>
  <tr><td height="20"></td></tr>
  <tr>
    <td colspan=3 align="center"><span class="design">&copy; Copyright 2007 Nathalie Steinmetz (nathalie.steinmetz'at'sti2.at</span>
    </td>
  </tr>
</table>
