    <table width="100%" border="0" cellspacing="0" cellpadding="0" align="center">
      <colgroup>
        <col width="200">
        <col>
        <col>
      </colgroup>

      <!-- row for space -->
      <tr>
        <td colspan="3">
          <table width="100%" border="0" cellpadding="10" cellspacing="0">
            <tr> <td></td> </tr>
          </table>
        </td>
      </tr>
      <tr>
        <td colspan="3" height="1" background="../Images/bluepixel.png"></td>
      </tr>

      <!-- row for username and crumbtrail -->
      <tr>
        <td align="left" bgcolor="#e6e6e6" valign="middle"> <a href="sti_library.php"><span style="color: #ff6600"><strong>STI-Innsbruck Library</strong></span></a></td>
        <td align="left" bgcolor="#e6e6e6" valign="middle"><strong>Location: </strong>

